<a href="https://colab.research.google.com/github/Rohan-Kumar11/machine-learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
df.shape

(150, 6)

In [4]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [6]:
y= df['Species']
x= df.drop('Species',axis=1)

In [8]:
x.shape

(150, 5)

In [17]:
x.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [9]:
y.shape

(150,)

In [13]:
from sklearn.model_selection  import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing  import StandardScaler
sc = StandardScaler()
x_train_transformed = pd.DataFrame(sc.fit_transform(x_train),columns=x_train.columns,index=x_train.index)

In [16]:
x_train_transformed.shape

(120, 5)

In [18]:
x_train_transformed.head()

           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137  1.346366       0.613030      0.108501       0.947518      0.736040
84   0.161847      -0.567766     -0.124001       0.384914      0.348083
27  -1.112070      -0.803926      1.038510      -1.302896     -1.333062
127  1.122872       0.258791     -0.124001       0.609956      0.736040
132  1.234619       0.613030     -0.589006       1.003778      1.253315

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 5, p=2 , metric='minkowski')
knn.fit(x_train_transformed,y_train)

KNeighborsClassifier()

In [25]:
knn.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [26]:
knn.effective_metric_

'euclidean'

In [27]:
knn.n_features_in_

5

In [28]:
x_test_transformed = pd.DataFrame(sc.transform(x_test),columns=x_test.columns,index=x_test.index)

In [31]:
x_test_transformed.shape

(30, 5)

In [32]:
y_test_pred = knn.predict(x_test_transformed)

In [33]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_test_pred)

1.0